pipeline {
	agent any
    stages {
		stage("Build") {
			steps {
				sh "echo 'is already built it'"
            }
        }

        stage('Docker Compose Up') {
			steps {
				sh '''
                    cd back
                    docker-compose -f docker-compose.yml up -d --build
                '''
            }
        }
    }

    post {
		always {
			sh '''
                cd back
                docker-compose down
            '''
            echo "Pipeline terminée"
        }
    }
}
