pipeline {
	agent any
    stages {
		stage("Build") {
			steps {
				sh "echo 'is already built it'"
            }
        }

        stage('Docker Up Discovery Service') {
			steps {
				sh '''
                    cd back/discovery-Client
                    docker run -d -p 8761:8761 --name discovery-service discovery-service:1.2
                '''
            }
        }
    }

    post {
		always {
			sh '''
                docker stop discovery-service || true
                docker rm discovery-service || true
            '''
            echo "Pipeline terminée"
        }
    }
}
