pipeline{
	agent any
	tools{
		python "python3"
	}
	environment{
		REMOTE_HOST="kali@192.168.25.139"
		IMAGE_NAME="matricule_detection_service"
	}
	stages{
		stage("Biuld images docker "){
            sh'''
            cd back/balance_service-main
            docker build -t $IMAGE_NAME:1.0 .
            docker run -p 8000:8000 --name $IMAGE_NAME $IMAGE_NAME :1.0
            '''
		}
		stage("deploy service"){
			sh'''
			cd back/balance_service-main
			docker save $IMAGE_NAME:1.0 | ssh $REMOTE_HOST "docker load"
			'''


		}
		stage("run application"){
			sh'''
			ssh $REMOTE_HOST
			docker run -d -p 8000:8000 -- name $IMAGE_NAME  $IMAGE_NAME:1.0
			'''


		}
	}
	post {
		always {
			sh '''
			docker stop $IMAGE_NAME
			docker rm $IMAGE_NAME
			'''
		}
	}
}